### ISSUE TITLE
Canvas Rendering Doesn't Initially Render

### ISSUE THREAD

**Issue by emeeks** [nteract/semiotic#609] opened 2022-01-20 06:22 UTC
The current examples don't seem to render when canvas rendering is set to true on the initial load. You can see this in the old docs in the canvas interaction or the XYFrame Overview docs when you set canvas rendering to "all". It's not clear when this happened.

**Comment by alexeyraspopov** [comment] 2022-01-20 15:42
I was able to reproduce this bug before and after #608 was merged. Will see what's happening under the hood

**Comment by alexeyraspopov** [comment] 2022-01-20 16:09
So "canvasinteraction" was failing due to diamonds.csv file being unable to load, I'm fixing it.

**Comment by alexeyraspopov** [comment] 2022-01-20 18:36
ok, I identified the issue with XYFrame Overview not rendering canvas after the props change. Seems like an actual bug somewhere between Frame and VisualizationLayer, gonna fix it as a part of the previously mentioned thing

**Closed** 2022-01-22 02:46 UTC
