### ISSUE TITLE
XY Brush component bug

### ISSUE THREAD

**Issue by moona3k** [nteract/semiotic#512] opened 2020-01-17 00:44 UTC
Live demo of the bug is found in the XY Brush example in the below link:
https://semiotic.nteract.io/guides/xy-brushes

Issue: **interaction** prop enables a brush-like interactive region that you can move and adjust width. When you click anywhere outside of the interactive region in the XYFrame component, the program crashes. Refer to screenshots below:

<img width="855" alt="Screen Shot 2020-01-16 at 4 40 14 PM" src="https://user-images.githubusercontent.com/32221114/72574728-e52a2280-387e-11ea-995e-1ef93592f3fc.png">

![Screen Shot 2020-01-16 at 4 37 34 PM](https://user-images.githubusercontent.com/32221114/72574627-85337c00-387e-11ea-859c-b060b0cce74a.png)

![Screen Shot 2020-01-16 at 4 42 19 PM](https://user-images.githubusercontent.com/32221114/72574794-30dccc00-387f-11ea-8e8b-d4186d167e38.png)

**Comment by emeeks** [comment] 2020-01-20 03:30
Do you see this happening in the local version or only in the online documentation? I need to update the online docs and I can't reproduce it locally so I think it's because the docs are a few versions back. I will dig into updating the docs now.

**Comment by emeeks** [comment] 2020-01-21 03:11
Fixed in `1.20.5`

**Closed by emeeks** 2020-01-21 03:11 UTC
