### ISSUE TITLE
Annotation Note Title Fails to Update

### ISSUE THREAD

**Issue by mph006** [nteract/semiotic#495] opened 2019-08-22 01:18 UTC
Data driven annotations don't seem to be updating with respect to changing state/props.

Replicated in this [CodePen](https://codepen.io/team/netflixui/pen/VwZmVRe)

Example Snippet:
```
render() {
	let annotations = [{
		type: "x",
		dy: -8,
		dx: 10,
		className: 'somethingClassy',
		xAxisName: whereToPlaceAnnotationOnXAxis,
		note: {
			title: `Title: ${this.props.changingAnnotationTitle}`,
			orientation: 'topBottom',
			align: 'top'
		}
	}]

    console.log("what should the note be: ", this.props.changingAnnotationTitle)

    return <XYFrame
    		{...otherSharedProps}
    		lines={this.props.inboundData}
    		annotations={annotations}
          />
}
```

This annotation's note will initialize as expected, with the first value of `this.props.changingAnnotationTitle`, however, when that value changes, the annotation's `tspan` does not update with respect to the latest passed value The `console.log` statement highlights the difference between the expected and rendered annotation note

Hitting the following error
```
semiotic.min.js:1 Uncaught TypeError: (0 , require$$1$6.topBottomDynamic) is not a function
    at exports.default (semiotic.min.js:1)
    at Note.render (semiotic.min.js:1)
    at react-dom.js:5257
    at measureLifeCyclePerf (react-dom.js:4537)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (react-dom.js:5256)
    at ReactCompositeComponentWrapper._renderValidatedComponent (react-dom.js:5283)
    at ReactCompositeComponentWrapper._updateRenderedComponent (react-dom.js:5207)
    at ReactCompositeComponentWrapper._performComponentUpdate (react-dom.js:5185)
    at ReactCompositeComponentWrapper.updateComponent (react-dom.js:5106)
    at ReactCompositeComponentWrapper.receiveComponent (react-dom.js:5008)
```

Temporary workaround for those encountering similar behavior:
Use the D3 update pattern to modify the `.text()` of `.somethingClassy`'s `tspan` in the `render()` function

**Comment by emeeks** [comment] 2019-09-03 01:56
This should be fixed in 1.20.3. Please feel free to reopen this and let me know if there's still an issue.

**Comment by mph006** [comment] 2019-09-03 16:18
I may be missing something here, but I am still able to recreate the error using **1.20.3** in the example [CodePen](https://codepen.io/team/netflixui/pen/VwZmVRe)

Please consider this a low priority item, and thanks again for the ongoing improvements to and maintenance of Semiotic

**Comment by emeeks** [comment] 2019-09-03 16:26
You're right, it sure is. I'll see what's still going wrong...

**Comment by torioLuz** [comment] 2020-01-17 23:36
@emeeks I also hit the same issue when all the XYFrame props didn't change except the annotation note props. The issue seems to be how semiotic merges the old and new annotation obj under a certain condition. 

I've located the code where the issue happens, and made a small [change](https://github.com/nteract/semiotic/pull/513) based on what I _think_ is the intended behavior.

**Comment by emeeks** [comment] 2020-03-22 02:23
I believe this has been fixed for a while now, let me know if not in a new issue.

**Closed by emeeks** 2020-03-22 02:23 UTC
