### ISSUE TITLE
 Each child in a list should have a unique "key" 

### ISSUE THREAD

**Issue by TijanaStojkov** [nteract/semiotic#499] opened 2019-09-05 15:51 UTC
I am getting a warning message for the waterfall chart:

Warning: Each child in a list should have a unique "key" prop.

How do I add a unique key to: 

return <OrdinalFrame {...frameProps} />;

**Comment by emeeks** [comment] 2019-10-19 20:08
Hi Tijana, the problem is that you're creating an array of elements in the waterfall function and returning that, so it's just the usual React issue that if you return an array of elements each of those elements should have a key. Just give every element you're returning `key={somethingUnique}` this could be as simple as array position or something a little more meaningful such as column name or something else recognzable.

**Comment by TijanaStojkov** [comment] 2019-10-24 18:57
Well, I know that but I could not find a way to do that. Could you give me an example on your waterfall chart https://semiotic.nteract.io/examples/waterfall-chart because it has the same issue?

**Comment by emeeks** [comment] 2020-03-22 02:22
Closing this because that example no longer has key errors. Feel free to open a new issue if you're still seeing problems with creating new elements without keys or with conflicting keys.

**Closed by emeeks** 2020-03-22 02:22 UTC
