### ISSUE TITLE
XYFrame x-axis tick not starting at origin

### ISSUE THREAD

**Issue by niwsa** [nteract/semiotic#450] opened 2019-04-04 06:56 UTC
Have a sandbox up and running at https://codesandbox.io/embed/10x4lrxq8q

![image](https://user-images.githubusercontent.com/3107922/55535408-c6361780-56d4-11e9-9d6c-3b50ad11de05.png)

As seen in the image x-axis tick 0 is not starting at the origin.

**Comment by emeeks** [comment] 2019-04-05 05:53
When I open this I don't see the same thing you've posted. Did you change some settings?
<img width="536" alt="Screen Shot 2019-04-04 at 10 51 38 PM" src="https://user-images.githubusercontent.com/495634/55606141-7e42df00-572c-11e9-9397-bcaa57940f8f.png">

**Comment by niwsa** [comment] 2019-04-05 06:00
Strange I didn't change anything, For me it appears the same as the image in my first comment with the x axis ticks starting from 0.I tried one or two things with the axes settings but I had reverted those.Hope you are seeing the below axes settings.
```axes={[
        {
          orient: "left",
          label: "kwh"
        },
        {
          orient: "bottom",
          label: { name: "Hours", locationDistance: 0 },
          tickFormat: d => d.getUTCHours()
        }
      ]}```

**Comment by emeeks** [comment] 2019-04-05 06:03
I've tried it on MacOS in Safari and Chrome what browser are you using? I wonder if there's something about `getUTCHours` going on.

**Comment by niwsa** [comment] 2019-04-05 06:03
I am on a ubuntu 16.04 chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by emeeks** [comment] 2019-04-05 06:13
How very strange. When I open that link I still see the chart that I posted a screenshot of.

**Comment by niwsa** [comment] 2019-04-05 06:22
What about the tooltips are they showing the correct info?

**Comment by emeeks** [comment] 2019-04-05 20:22
Seems like it.

<img width="341" alt="Screen Shot 2019-04-05 at 1 19 40 PM" src="https://user-images.githubusercontent.com/495634/55654222-a884b300-57a5-11e9-9395-bb9bb8a2c48e.png">

As far as which ticks are rendered, that's a long-standing area of research. Under the hood, `d3-scale` uses what are known as "nice" ticks that can sometimes not be what you wanted. You can pass an array of `tickValues` or a number of `ticks` to get more control of that.

**Comment by niwsa** [comment] 2019-04-08 11:17
Thank you for clarifying.So ` tickValues: d =>  d.map(d => d.x)` fixes the issue for me.You can see it in the sandbox. However `ticks` attribute didn't have any effect with `tickValues` enabled.But still stumped by the x-tick mismatch between our systems.

**Comment by emeeks** [comment] 2019-05-14 17:08
Closing this because I cannot reproduce it.

**Closed by emeeks** 2019-05-14 17:08 UTC
